1.3.1. The NumPy array object
1.3.1.1. What are NumPy and NumPy arrays?

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([range(5,10)])
print(a, b)

[1 2 3 4] [[5 6 7 8 9]]


In [2]:
L = range(1000)
%timeit [  i**2 for i in L]

59.4 μs ± 52.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

767 ns ± 2.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [12]:
np.array([1,2,3])

array([1, 2, 3])

In [11]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [10]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [13]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [14]:
np.array([1+0.1j, 2+.2j, 3+1j],dtype=complex)

array([1.+0.1j, 2.+0.2j, 3.+1.j ])

In [20]:
np_str = np.arange(10).astype('S')
np_str1 = np.arange(11,20,2).astype('S')
print(np_str.dtype, np_str, np_str1.dtype, np_str1)

|S21 [b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9'] |S21 [b'11' b'13' b'15' b'17' b'19']


In [41]:
x = np.array([[1,2],[3,4]],dtype=[('a','i'),('b','i')])
print(f'x:{x}\n x[\'a\']:{x[0]}')

x:[[(1, 1) (2, 2)]
 [(3, 3) (4, 4)]]
 x['a']:[(1, 1) (2, 2)]


In [42]:
x = np.array([(1,2),(3,4)],dtype=[('a','i'),('b','i')])
print(f'x:{x}\n x[\'a\']:{x[0]}')

x:[(1, 2) (3, 4)]
 x['a']:(1, 2)


In [46]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [49]:
mt = np.asmatrix('1 2 ; 3 4')
a = np.array(mt)
a

array([[1, 2],
       [3, 4]])

In [51]:
# '1 2; 3 4' 문자열로 matrix 생성
mat = np.asmatrix('1 2; 3 4')
print(f"Original matrix type: {type(mat)}{mat}")

# subok=False (기본값): matrix를 ndarray로 강제 변환
arr_no_subok = np.array(mat, subok=False)
print(f"Result with subok=False: {type(arr_no_subok)}{arr_no_subok}")

# subok=True: matrix 타입을 유지
arr_subok = np.array(mat, subok=True)
print(f"Result with subok=True: {type(arr_subok)}{arr_subok}")

Original matrix type: <class 'numpy.matrix'>[[1 2]
 [3 4]]
Result with subok=False: <class 'numpy.ndarray'>[[1 2]
 [3 4]]
Result with subok=True: <class 'numpy.matrix'>[[1 2]
 [3 4]]


#numpy array와 matrix의 차이가 뭐야
Numpy ndarray와 matrix는 둘 다 행렬 형태의 데이터를 다루지만, ndarray가 Numpy의 기본 데이터 구조이며, matrix는 특정한 행렬 연산을 위해 만들어진 클래스입니다.

1. 차원 (Dimension)
ndarray: 1차원, 2차원, 3차원 등 다차원(N-dimensional) 배열을 표현할 수 있습니다.
matrix: 오직 2차원 행렬만 표현할 수 있습니다.

1. 연산자 (Operator)
이것이 가장 큰 차이점입니다.

* 연산자:
ndarray: 요소별 곱셈(element-wise multiplication)을 수행합니다. 즉, 두 배열의 같은 위치에 있는 요소끼리 곱합니다. 행렬 곱셈을 하려면 @ 연산자 또는 np.dot() 함수를 사용해야 합니다.
matrix: 기본적으로 **행렬 곱셈(matrix multiplication)**을 수행합니다.

3. 전치 (Transpose)
ndarray: .T 속성을 사용해 전치할 수 있습니다. 예를 들어 arr.T.
matrix: .T 외에 .H(Hermitian transpose, 켤레 복소 전치)도 지원합니다.

4. 권장 사항
ndarray: 대부분의 상황에서 ndarray 사용을 권장합니다. matrix는 특정 용도를 위해 존재하지만, ndarray의 기능이 더 풍부하고 현대적인 Numpy 생태계와 더 잘 맞습니다. Numpy 문서에서도 matrix보다는 ndarray를 사용하라고 권장하고 있습니다.
matrix: ndarray와 matrix의 연산 방식 차이 때문에 혼란이 생길 수 있으므로, 행렬 연산이 필요한 경우 ndarray에 @ 연산자를 사용하는 것이 더 명확하고 일관적입니다.

In [52]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

mat1 = np.matrix([[1, 2], [3, 4]])
mat2 = np.matrix([[5, 6], [7, 8]])

# ndarray는 요소별 곱셈
print(f"ndarray * : \n{arr1 * arr2}\n")

# matrix는 행렬 곱셈
print(f"matrix * : \n{mat1 * mat2}\n")

# ndarray로 행렬 곱셈을 하려면 @ 또는 dot() 사용
print(f"ndarray @ : \n{arr1 @ arr2}\n")

ndarray * : 
[[ 5 12]
 [21 32]]

matrix * : 
[[19 22]
 [43 50]]

ndarray @ : 
[[19 22]
 [43 50]]



In [54]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [55]:
np.con*?

np.concat
np.concatenate
np.conj
np.conjugate
np.convolve

In [60]:
np.a*?

np.abs
np.absolute
np.acos
np.acosh
np.add
np.all
np.allclose
np.amax
np.amin
np.angle
np.any
np.append
np.apply_along_axis
np.apply_over_axes
np.arange
np.arccos
np.arccosh
np.arcsin
np.arcsinh
np.arctan
np.arctan2
np.arctanh
np.argmax
np.argmin
np.argpartition
np.argsort
np.argwhere
np.around
np.array
np.array2string
np.array_equal
np.array_equiv
np.array_repr
np.array_split
np.array_str
np.asanyarray
np.asarray
np.asarray_chkfinite
np.ascontiguousarray
np.asfortranarray
np.asin
np.asinh
np.asmatrix
np.astype
np.atan
np.atan2
np.atanh
np.atleast_1d
np.atleast_2d
np.atleast_3d
np.average

##1.3.1.2. Creating arrays

In [67]:
a = np.array([1,2,3,4])
print('a,shape',a.shape,'a.ndim', a.ndim, 'len',len(a))

a,shape (4,) a.ndim 1 len 4


In [66]:
b= np.array([[1,2,3],[4,5,6]])
print('b,shape',b.shape,'b.ndim', b.ndim, 'len', len(b))

b,shape (2, 3) b.ndim 2 len 2


In [71]:
c=np.array([  [[1],[2],[3]], [[4],[5],[6]]] )
print('c,shape',c.shape,'c.ndim', c.ndim, 'len', len(c))

c,shape (2, 3, 1) c.ndim 3 len 2


Functions for creating arrays

In [74]:
a = np.arange(10)
b = np.arange(1,10,3)
c = np.linspace(1,10,5)
d = np.linspace(1,10,5, endpoint=False)
print(a,b,c, d, sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[1 4 7]
[ 1.    3.25  5.5   7.75 10.  ]
[1.  2.8 4.6 6.4 8.2]


Common arrays:

In [78]:
a = np.ones(5)
b = np.zeros(5)
c = np.eye(4)
d = np.diag(np.array([1,2,3,4]))
for ch, nparray in zip('abcd',[a,b,c,d]):
    print(ch,nparray)
    #print(a,b,c, d, sep='\n')

a [1. 1. 1. 1. 1.]
b [0. 0. 0. 0. 0.]
c [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
d [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


np.random: random numbers (Mersenne Twister PRNG):